server:
  port: 8020
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: users
          uri: lb://user-ms
          predicates:
            - Path=/users/status
            - Method=GET


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

